# AUTORES: RICARDO FUENTES, VALERY FERNANDEZ, JUAN LUIS SUCERQUIA, MARIANA SANCHEZ
from enum import Enum

class Ubicacion(Enum):

    PASILLO = 'PASILLO'
    VENTANA = 'VENTANA'
    CENTRAL = 'CENTRAL'